import { Category, Product, NavItem } from "@/types";

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Himalayan Dawn",
    category: Category.ABSTRACT,
    price: 2400,
    materials: ["Wool", "Silk"],
    colors: ["Beige", "Gold"],
    sizes: ["170x240", "200x300"],
    image: "https://picsum.photos/800/1000?random=1",
    isNew: true,
    knotDensity: 100,
  },
  {
    id: "2",
    name: "Tibetan Shadow",
    category: Category.SHADED,
    price: 1800,
    materials: ["Wool"],
    colors: ["Grey", "Black"],
    sizes: ["140x200", "170x240"],
    image: "https://picsum.photos/800/1000?random=2",
    isNew: false,
    knotDensity: 80,
  },
  {
    id: "3",
    name: "Lotus Valley",
    category: Category.FLOWER,
    price: 3200,
    materials: ["Wool", "Silk", "Allo"],
    colors: ["Red", "Cream"],
    sizes: ["200x300", "250x350"],
    image: "https://picsum.photos/800/1000?random=3",
    isNew: true,
    knotDensity: 100,
  },
  {
    id: "4",
    name: "Minimal Border",
    category: Category.BORDER,
    price: 1500,
    materials: ["Wool", "Hemp"],
    colors: ["White", "Brown"],
    sizes: ["120x180", "140x200"],
    image: "https://picsum.photos/800/1000?random=4",
    isNew: false,
    knotDensity: 60,
  },
  {
    id: "5",
    name: "Urban Stripes",
    category: Category.STRIPES,
    price: 2100,
    materials: ["Wool", "Linen"],
    colors: ["Blue", "Grey"],
    sizes: ["170x240"],
    image: "https://picsum.photos/800/1000?random=5",
    isNew: true,
    knotDensity: 80,
  },
  {
    id: "6",
    name: "Modern Earth",
    category: Category.CONTEMPORARY,
    price: 2800,
    materials: ["Wool", "Silk"],
    colors: ["Brown", "Green"],
    sizes: ["200x300", "250x350"],
    image: "https://picsum.photos/800/1000?random=6",
    isNew: false,
    knotDensity: 100,
  },
];

export const NAV_ITEMS: NavItem[] = [
  { label: "Home", href: "/" },
  {
    label: "Shop",
    href: "/shop",
    children: [
      { label: "New Arrivals", href: "/shop?filter=new" },
      { label: "All Stock", href: "/shop" },
    ],
  },
  {
    label: "Collections",
    href: "#",
    children: [
      { label: "Contemporary", href: "/collections/Contemporary" },
      { label: "Shaded", href: "/collections/Shaded" },
      { label: "Flower", href: "/collections/Flower" },
      { label: "Border", href: "/collections/Border" },
      { label: "Stripes", href: "/collections/Stripes" },
      { label: "Abstract", href: "/collections/Abstract" },
    ],
  },
  {
    label: "Bespoke",
    href: "/custom-rugs",
    children: [
      { label: "Overview", href: "/custom-rugs" },
      { label: "Customize Existing", href: "/custom-rugs/customize" },
      { label: "Design Your Own", href: "/custom-rugs/bespoke" },
    ],
  },
  {
    label: "About",
    href: "/about",
    children: [
      { label: "Our Culture", href: "/about/culture" },
      { label: "Meet the Founder", href: "/about/founder" },
      { label: "Art of Weaving", href: "/about/weaving" },
    ],
  },
  { label: "Assistance", href: "/assistance" },
];
