"use client";

import { motion, Variants } from "motion/react";
import { sanitizeHtmlContent } from "@/utils/htmlSanitizer";

const fadeInUp: Variants = {
  hidden: { opacity: 0, y: 20 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { duration: 0.6, ease: "easeOut" },
  },
};

const PRIVACY_SECTIONS = [
  {
    title: "Introduction",
    content: `
      <p>
        Rugkala (“we”, “our”, or “us”) is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by Rugkala.
      </p>
      <p>
        This Privacy Policy applies to our website, www.rugkala.com, and its associated subdomains (collectively, our “service”). By accessing or using our service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and Terms of service.
      </p>
    `,
  },
  {
    title: "Definitions & Key Terms",
    content: `
      <p>To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly defined as:</p>
      <ul class="list-disc pl-5 space-y-2 mt-2">
        <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your login information or language preference.</li>
        <li><strong>Company:</strong> when this policy mentions “Company”, “we”, “us” or “our”, it refers to Rugkala, Bouddha, Kathmandu, Nepal that is responsible for your information under this Privacy Policy.</li>
        <li><strong>Country:</strong> where Rugkala or the owners/founders of Rugkala are based, in this case is Nepal.</li>
        <li><strong>Customer:</strong> refers to the company, organization or person that signs up to use the Rugkala service to manage the relationships with consumers or service users.</li>
        <li><strong>Device:</strong> any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Rugkala and use the services.</li>
        <li><strong>IP address:</strong> Every device connected to the internet is assigned a number known as an Internet Protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.</li>
        <li><strong>Personnel:</strong> refers to those individuals who are employed by Rugkala or are under contract to perform a service on behalf of one of the parties.</li>
        <li><strong>Personal Data:</strong> any information that directly, indirectly, or in connection with other information - including a Personal Identification Number (PIN) - allows for the identification of identifiability of a natural person.</li>
        <li><strong>Service:</strong> refers to the service provided by Rugkala as described in the relative terms (if available) and on this platform.</li>
        <li><strong>Third-party service:</strong> refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</li>
        <li><strong>Website:</strong> Rugkala’s site, which can be accessed via this URL: www.rugkala.com.</li>
        <li><strong>You:</strong> a person or entity that is registered with Rugkala to use the services.</li>
      </ul>
    `,
  },
  {
    title: "What Information Do We Collect?",
    content: `
      <p>When you visit our service, we collect information from you, register, place an order, subscribe to our newsletter, respond to a survey or fill out a form.</p>
      <ul class="list-disc pl-5 space-y-2 mt-2">
        <li>Name/Username</li>
        <li>Phone Numbers</li>
        <li>Email Addresses</li>
        <li>Mailing Addresses</li>
        <li>Billing Addresses</li>
        <li>Debit/Credit Card Numbers</li>
        <li>Password</li>
      </ul>
      <p>We also collect information from mobile devices for a better user experience, although these features are completely optional:</p>
       <ul class="list-disc pl-5 space-y-2 mt-2">
        <li>Location (GPS): Location data helps to accurately represent your interests, which we will use to bring more targeted and relevant ads to potential customers.</li>
      </ul>
    `,
  },
  {
    title: "How Do We Use The Information We Collect?",
    content: `
      <p>We use the information we collect from you in the following ways:</p>
      <ul class="list-disc pl-5 space-y-2 mt-2">
        <li>To personalize your experience (your information helps us to better respond to your individual needs)</li>
        <li>To improve our service (we continually strive to improve our service offerings based on the information and feedback we receive from you)</li>
        <li>To improve customer service (your information helps us to respond to your customer service requests and support needs more effectively)</li>
        <li>To process transactions</li>
        <li>To administer a contest, promotion, survey or other site feature</li>
        <li>To send periodic emails</li>
      </ul>
    `,
  },
  {
    title: "When Do We Use Customer Information From Third Parties?",
    content: `
        <p>We receive some information from third parties when you contact us. For example, when you submit your email address to us to show interest in becoming our customer, we receive information from a third party providing automated fraud detection services. We also occasionally collect information that is made publicly available on social media websites. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.</p>
    `
  },
  {
    title: "Governing Law",
    content: `
      <p>The laws of Nepal, excluding its conflicts of law rules, shall govern this agreement and your use of our service. Your use of our service may also be subject to other local, state, national, or international laws.</p>
    `
  },
  {
    title: "Your Consent",
    content: `
      <p>By using our service, registering an account, or making a purchase, you consent to this Privacy Policy.</p>
    `
  },
  {
    title: "Contact Us",
    content: `
      <p>Don’t hesitate to contact us if you have any questions.</p>
      <ul class="list-disc pl-5 space-y-2 mt-2">
        <li>Via Email: shop@rugkala.com</li>
        <li>Via Address: Bouddha, Kathmandu, Nepal</li>
      </ul>
    `,
  },
];

const Section: React.FC<{ title: string; content: string }> = ({
  title,
  content,
}) => (
  <div className="mb-10">
    <h3 className="text-3xl font-bold font-serif mb-4 text-primary">{title}</h3>
    <div
      className="text-gray-600 font-serif leading-relaxed space-y-4"
      dangerouslySetInnerHTML={{ __html: sanitizeHtmlContent(content) }}
    />
  </div>
);

export const PrivacyPolicy: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto px-6 py-16 md:py-24">
      <motion.div
        initial="hidden"
        animate="visible"
        variants={fadeInUp}
        className="space-y-12"
      >
        <div className="text-center space-y-4 mb-16">
          <span className="text-xs font-bold uppercase tracking-widest text-accent block">
            Legal Information
          </span>
          <h1 className="text-4xl md:text-5xl font-serif leading-tight">
            Privacy Policy
          </h1>
          <p className="text-gray-500 font-serif italic">
            Last updated: {new Date().toLocaleDateString("en-US", { month: "long", year: "numeric" })}
          </p>
        </div>

        {PRIVACY_SECTIONS.map((section, index) => (
          <Section key={index} title={section.title} content={section.content} />
        ))}
      </motion.div>
    </div>
  );
};
